### ISSUE TITLE
Live doesn't work

### ISSUE THREAD

**Issue by jcronan-slcc** [xhlove/XstreamDL-CLI#32]
Hi, when I try to record live MPD stream, I've been told to report it because it seems to not work

```
D:\XstreamDL-CLI-master>python -m XstreamDL_CLI.cli --live --name "test2" "https://tglmp02.akamaized.net/out/v1/9fd968b813e5405194a4fc3db1baae0e/manifest.mpd"
2021-11-28 17:57:38,199 XstreamDL log.py 41 : INFO  log file -> D:/XstreamDL-CLI-master/logs/XstreamDL-2021-11-28_175738.log
2021-11-28 17:57:38,215 XstreamDL cli.py 152 : INFO  set URI to ['https://tglmp02.akamaized.net/out/v1/9fd968b813e5405194a4fc3db1baae0e/manifest.mpd']
Traceback (most recent call last):
  File "C:\Users\ryank\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ryank\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\XstreamDL-CLI-master\XstreamDL_CLI\cli.py", line 160, in <module>
    main()
  File "D:\XstreamDL-CLI-master\XstreamDL_CLI\cli.py", line 154, in main
    daemon.daemon()
  File "D:\XstreamDL-CLI-master\XstreamDL_CLI\daemon.py", line 30, in daemon
    streams = extractor.fetch_metadata(self.args.URI[0])
  File "D:\XstreamDL-CLI-master\XstreamDL_CLI\extractor.py", line 48, in fetch_metadata
    return self.raw2streams('url', *loop.run_until_complete(self.fetch(uri)), parent_stream)
  File "D:\XstreamDL-CLI-master\XstreamDL_CLI\extractor.py", line 95, in raw2streams
    return self.parse_as_dash(uri_type, uri, content, parent_stream)
  File "D:\XstreamDL-CLI-master\XstreamDL_CLI\extractor.py", line 127, in parse_as_dash
    streams = self.parser.parse(uri, content)
  File "D:\XstreamDL-CLI-master\XstreamDL_CLI\extractors\dash\parser.py", line 132, in parse
    return self.walk_period(mpd, uri_item.new_base_url(base_url))
  File "D:\XstreamDL-CLI-master\XstreamDL_CLI\extractors\dash\parser.py", line 149, in walk_period
    _streams = self.walk_adaptationset(period, len(streams), uri_item.new_base_url(base_url))
  File "D:\XstreamDL-CLI-master\XstreamDL_CLI\extractors\dash\parser.py", line 177, in walk_adaptationset
    _streams = self.walk_representation(adaptationset, period, sindex + len(streams), current_uri_item)
  File "D:\XstreamDL-CLI-master\XstreamDL_CLI\extractors\dash\parser.py", line 236, in walk_representation
    self.walk_segmenttemplate(representation, period, stream)
  File "D:\XstreamDL-CLI-master\XstreamDL_CLI\extractors\dash\parser.py", line 296, in walk_segmenttemplate
    self.walk_segmenttimeline(segmenttemplates[0], representation, period, stream)
  File "D:\XstreamDL-CLI-master\XstreamDL_CLI\extractors\dash\parser.py", line 306, in walk_segmenttimeline
    self.walk_s(segmenttimelines[0], segmenttemplate, representation, period, stream)
  File "D:\XstreamDL-CLI-master\XstreamDL_CLI\extractors\dash\parser.py", line 335, in walk_s
    assert isinstance(self.root.availabilityStartTime, float), 'report mpd to me'
AssertionError: report mpd to me
```

I hope you can help on this, thank you!

**Comment by xhlove** [comment]
fixed https://github.com/xhlove/XstreamDL-CLI/commit/8201f417bb9e98cf955d0813c197bc74005e717c

and suggest to use
- `--select` to choose track
- `--key kid...:key...` to do decrypt
- `--live-duration ...` to set recoed time
use `python -m XstreamDL_CLI.cli -h` to get more help info
