### ISSUE TITLE
直播无法下载

### ISSUE THREAD

**Issue by 362227** [xhlove/XstreamDL-CLI#34]
https://playlist.fubo.tv/master.mpd?alternate-feed=0&callsign=KTNV&cdn_cache_key=S1ROVi1kZXNrdG9wLVVTQS04OTAzMi04OTEwMS0wLTAtREFTSC0wLTA%3D&cookie_supported_platform=1&device=ALL&hdnts=ip%3D66.187.4.21~st%3D1639621403~exp%3D1639707803~acl%3D%2F%2A~data%3D1639707803~hmac%3D2ef355cd8643174c4f123f9095c701fc54ed78d571b0a87325963f292f71b0c6&is_kvtdb=0&watchToken=eyJhbGciOiJIUzI1NiIsInRva2VuVHlwZSI6IlVzYUJhc2VXYXRjaFRva2VuIiwidHlwIjoiSldUIn0.eyJ3YXRjaFRva2VuIjp7ImNhbGxTaWduIjoiS1ROViIsImRldmljZSI6IkFMTCIsImJhbmR3aWR0aCI6Ik1BU1RFUiIsImNvdW50cnkiOiJVU0EiLCJ1c2VySWQiOiI2MTliNTg3MWJhZmY3MTAwMDFkMTQzNDIiLCJyZXF1ZXN0VHlwZSI6ImxpdmUiLCJyZWdpb24iOiJ3ZXN0In0sImhvbWVaaXAiOiI4OTAzMiIsImdlb1ppcCI6Ijg5MTAxIn0.j9AhzliF_tqiQD6GCwDkM_A2QN6VwzhU3-sdWA4C5AE

**Comment by xhlove** [comment]
1. 403 无法访问
2. 请按照readme的反馈要点进行反馈

**Comment by 362227** [comment]
需要美国ip 
[master.zip](https://github.com/xhlove/XstreamDL-CLI/files/7724573/master.zip)

**Comment by xhlove** [comment]
请提供日志和报错截图，使用的命令

**Comment by 362227** [comment]
![QQ截图20211216130432](https://user-images.githubusercontent.com/91358231/146311555-3c22fe16-bca9-46ea-b69d-b6ed73482886.jpg)


`2021-12-16 13:03:26,745 XstreamDL log.py 41 : INFO  log file -> D:/XstreamDL-CLI-master/XstreamDL-CLI-master/logs/XstreamDL-2021-12-16_130326.log
2021-12-16 13:03:26,745 XstreamDL cli.py 35 : DEBUG  set --live-duration to 0.0
2021-12-16 13:03:26,746 XstreamDL cli.py 41 : DEBUG  set --save-dir to D:/XstreamDL-CLI-master/XstreamDL-CLI-master/Downloads
2021-12-16 13:03:26,746 XstreamDL default.py 25 : DEBUG  use headers:
{
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36"
}
2021-12-16 13:03:26,746 XstreamDL cli.py 44 : DEBUG  set --limit-per-host to 4
2021-12-16 13:03:26,746 XstreamDL cli.py 50 : DEBUG  set --key to None
2021-12-16 13:03:26,746 XstreamDL cli.py 59 : DEBUG  set --b64key to None
2021-12-16 13:03:26,746 XstreamDL cli.py 60 : DEBUG  set --hexiv to None
2021-12-16 13:03:26,747 XstreamDL cli.py 80 : DEBUG  ffmpeg D:/XstreamDL-CLI-master/XstreamDL-CLI-master/binaries/ffmpeg.exe
2021-12-16 13:03:26,747 XstreamDL cli.py 81 : DEBUG  mp4decrypt D:/XstreamDL-CLI-master/XstreamDL-CLI-master/binaries/mp4decrypt.exe
2021-12-16 13:03:26,747 XstreamDL cli.py 82 : DEBUG  mp4box D:/XstreamDL-CLI-master/XstreamDL-CLI-master/binaries/mp4box.exe
2021-12-16 13:03:26,747 XstreamDL cli.py 152 : INFO  set URI to ['https://playlist.fubo.tv/master.mpd?alternate-feed=0&callsign=KTNV&cdn_cache_key=S1ROVi1kZXNrdG9wLVVTQS04OTAzMi04OTEwMS0wLTAtREFTSC0wLTA%3D&cookie_supported_platform=1&device=ALL&hdnts=ip%3D66.187.4.21~st%3D1639621403~exp%3D1639707803~acl%3D%2F%2A~data%3D1639707803~hmac%3D2ef355cd8643174c4f123f9095c701fc54ed78d571b0a87325963f292f71b0c6&is_kvtdb=0&watchToken=eyJhbGciOiJIUzI1NiIsInRva2VuVHlwZSI6IlVzYUJhc2VXYXRjaFRva2VuIiwidHlwIjoiSldUIn0.eyJ3YXRjaFRva2VuIjp7ImNhbGxTaWduIjoiS1ROViIsImRldmljZSI6IkFMTCIsImJhbmR3aWR0aCI6Ik1BU1RFUiIsImNvdW50cnkiOiJVU0EiLCJ1c2VySWQiOiI2MTliNTg3MWJhZmY3MTAwMDFkMTQzNDIiLCJyZXF1ZXN0VHlwZSI6ImxpdmUiLCJyZWdpb24iOiJ3ZXN0In0sImhvbWVaaXAiOiI4OTAzMiIsImdlb1ppcCI6Ijg5MTAxIn0.j9AhzliF_tqiQD6GCwDkM_A2QN6VwzhU3-sdWA4C5AE']
2021-12-16 13:03:27,846 XstreamDL base.py 35 : DEBUG  start parse uri for: https://playlist.fubo.tv/master.mpd?alternate-feed=0&callsign=KTNV&cdn_cache_key=S1ROVi1kZXNrdG9wLVVTQS04OTAzMi04OTEwMS0wLTAtREFTSC0wLTA%3D&cookie_supported_platform=1&device=ALL&hdnts=ip%3D66.187.4.21~st%3D1639621403~exp%3D1639707803~acl%3D/*~data%3D1639707803~hmac%3D2ef355cd8643174c4f123f9095c701fc54ed78d571b0a87325963f292f71b0c6&is_kvtdb=0&watchToken=eyJhbGciOiJIUzI1NiIsInRva2VuVHlwZSI6IlVzYUJhc2VXYXRjaFRva2VuIiwidHlwIjoiSldUIn0.eyJ3YXRjaFRva2VuIjp7ImNhbGxTaWduIjoiS1ROViIsImRldmljZSI6IkFMTCIsImJhbmR3aWR0aCI6Ik1BU1RFUiIsImNvdW50cnkiOiJVU0EiLCJ1c2VySWQiOiI2MTliNTg3MWJhZmY3MTAwMDFkMTQzNDIiLCJyZXF1ZXN0VHlwZSI6ImxpdmUiLCJyZWdpb24iOiJ3ZXN0In0sImhvbWVaaXAiOiI4OTAzMiIsImdlb1ppcCI6Ijg5MTAxIn0.j9AhzliF_tqiQD6GCwDkM_A2QN6VwzhU3-sdWA4C5AE
2021-12-16 13:03:27,846 XstreamDL base.py 18 : DEBUG  fix name before: master
2021-12-16 13:03:27,846 XstreamDL base.py 23 : DEBUG  fix name after: master
2021-12-16 13:03:27,847 XstreamDL base.py 63 : DEBUG  parse uri result:
    name master
    home_url https://playlist.fubo.tv
    base_url https://playlist.fubo.tv
2021-12-16 13:03:27,847 XstreamDL base.py 28 : DEBUG  save content to D:/XstreamDL-CLI-master/XstreamDL-CLI-master/Downloads/master.mpd, size 8326
2021-12-16 13:03:27,851 XstreamDL parser.py 52 : DEBUG  [fix_dash_base_url] previous_base_url https://playlist.fubo.tv
2021-12-16 13:03:27,851 XstreamDL parser.py 52 : DEBUG  [fix_dash_base_url] previous_base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:27,851 XstreamDL parser.py 52 : DEBUG  [fix_dash_base_url] previous_base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:27,851 XstreamDL parser.py 52 : DEBUG  [fix_dash_base_url] previous_base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:27,851 XstreamDL parser.py 198 : DEBUG  [DASHStream] base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:27,852 XstreamDL parser.py 339 : DEBUG  mpd.presentationTimeOffset 0 timescale 90000
2021-12-16 13:03:27,852 XstreamDL parser.py 340 : DEBUG  mpd.availabilityStartTime 1625039231.0 Period.start 0.0
2021-12-16 13:03:27,852 XstreamDL parser.py 341 : DEBUG  start_utctime 1625039261.0 current_utctime 1639602204.0
2021-12-16 13:03:27,852 XstreamDL parser.py 347 : DEBUG  set base_time 1310664635280 target_r 22
2021-12-16 13:03:27,852 XstreamDL parser.py 52 : DEBUG  [fix_dash_base_url] previous_base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:27,852 XstreamDL parser.py 198 : DEBUG  [DASHStream] base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:27,852 XstreamDL parser.py 339 : DEBUG  mpd.presentationTimeOffset 0 timescale 90000
2021-12-16 13:03:27,852 XstreamDL parser.py 340 : DEBUG  mpd.availabilityStartTime 1625039231.0 Period.start 0.0
2021-12-16 13:03:27,852 XstreamDL parser.py 341 : DEBUG  start_utctime 1625039261.0 current_utctime 1639602204.0
2021-12-16 13:03:27,852 XstreamDL parser.py 347 : DEBUG  set base_time 1310664635280 target_r 22
2021-12-16 13:03:27,852 XstreamDL parser.py 52 : DEBUG  [fix_dash_base_url] previous_base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:27,852 XstreamDL parser.py 198 : DEBUG  [DASHStream] base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:27,852 XstreamDL parser.py 339 : DEBUG  mpd.presentationTimeOffset 0 timescale 90000
2021-12-16 13:03:27,852 XstreamDL parser.py 340 : DEBUG  mpd.availabilityStartTime 1625039231.0 Period.start 0.0
2021-12-16 13:03:27,852 XstreamDL parser.py 341 : DEBUG  start_utctime 1625039261.0 current_utctime 1639602204.0
2021-12-16 13:03:27,853 XstreamDL parser.py 347 : DEBUG  set base_time 1310664635280 target_r 22
2021-12-16 13:03:27,853 XstreamDL parser.py 52 : DEBUG  [fix_dash_base_url] previous_base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:27,853 XstreamDL parser.py 198 : DEBUG  [DASHStream] base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:27,853 XstreamDL parser.py 339 : DEBUG  mpd.presentationTimeOffset 0 timescale 90000
2021-12-16 13:03:27,853 XstreamDL parser.py 340 : DEBUG  mpd.availabilityStartTime 1625039231.0 Period.start 0.0
2021-12-16 13:03:27,853 XstreamDL parser.py 341 : DEBUG  start_utctime 1625039261.0 current_utctime 1639602204.0
2021-12-16 13:03:27,853 XstreamDL parser.py 347 : DEBUG  set base_time 1310664635280 target_r 22
2021-12-16 13:03:27,853 XstreamDL parser.py 52 : DEBUG  [fix_dash_base_url] previous_base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:27,853 XstreamDL parser.py 198 : DEBUG  [DASHStream] base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:27,853 XstreamDL parser.py 339 : DEBUG  mpd.presentationTimeOffset 0 timescale 90000
2021-12-16 13:03:27,853 XstreamDL parser.py 340 : DEBUG  mpd.availabilityStartTime 1625039231.0 Period.start 0.0
2021-12-16 13:03:27,853 XstreamDL parser.py 341 : DEBUG  start_utctime 1625039261.0 current_utctime 1639602204.0
2021-12-16 13:03:27,853 XstreamDL parser.py 347 : DEBUG  set base_time 1310664635280 target_r 22
2021-12-16 13:03:27,853 XstreamDL parser.py 52 : DEBUG  [fix_dash_base_url] previous_base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:27,853 XstreamDL parser.py 52 : DEBUG  [fix_dash_base_url] previous_base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:27,853 XstreamDL parser.py 198 : DEBUG  [DASHStream] base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:27,853 XstreamDL parser.py 339 : DEBUG  mpd.presentationTimeOffset 0 timescale 48000
2021-12-16 13:03:27,853 XstreamDL parser.py 340 : DEBUG  mpd.availabilityStartTime 1625039231.0 Period.start 0.0
2021-12-16 13:03:27,853 XstreamDL parser.py 341 : DEBUG  start_utctime 1625039261.0 current_utctime 1639602204.0
2021-12-16 13:03:27,854 XstreamDL parser.py 347 : DEBUG  set base_time 699021139007 target_r 22
2021-12-16 13:03:27,854 XstreamDL daemon.py 78 : INFO  refresh link https://playlist.fubo.tv/master.mpd?alternate-feed=0&callsign=KTNV&cdn_cache_key=S1ROVi1kZXNrdG9wLVVTQS04OTAzMi04OTEwMS0wLTAtREFTSC0wLTA%3D&cookie_supported_platform=1&device=ALL&hdnts=ip%3D66.187.4.21~st%3D1639621403~exp%3D1639707803~acl%3D%2F%2A~data%3D1639707803~hmac%3D2ef355cd8643174c4f123f9095c701fc54ed78d571b0a87325963f292f71b0c6&is_kvtdb=0&watchToken=eyJhbGciOiJIUzI1NiIsInRva2VuVHlwZSI6IlVzYUJhc2VXYXRjaFRva2VuIiwidHlwIjoiSldUIn0.eyJ3YXRjaFRva2VuIjp7ImNhbGxTaWduIjoiS1ROViIsImRldmljZSI6IkFMTCIsImJhbmR3aWR0aCI6Ik1BU1RFUiIsImNvdW50cnkiOiJVU0EiLCJ1c2VySWQiOiI2MTliNTg3MWJhZmY3MTAwMDFkMTQzNDIiLCJyZXF1ZXN0VHlwZSI6ImxpdmUiLCJyZWdpb24iOiJ3ZXN0In0sImhvbWVaaXAiOiI4OTAzMiIsImdlb1ppcCI6Ijg5MTAxIn0.j9AhzliF_tqiQD6GCwDkM_A2QN6VwzhU3-sdWA4C5AE
2021-12-16 13:03:31,922 XstreamDL base.py 35 : DEBUG  start parse uri for: https://playlist.fubo.tv/master.mpd?alternate-feed=0&callsign=KTNV&cdn_cache_key=S1ROVi1kZXNrdG9wLVVTQS04OTAzMi04OTEwMS0wLTAtREFTSC0wLTA%3D&cookie_supported_platform=1&device=ALL&hdnts=ip%3D66.187.4.21~st%3D1639621403~exp%3D1639707803~acl%3D/*~data%3D1639707803~hmac%3D2ef355cd8643174c4f123f9095c701fc54ed78d571b0a87325963f292f71b0c6&is_kvtdb=0&watchToken=eyJhbGciOiJIUzI1NiIsInRva2VuVHlwZSI6IlVzYUJhc2VXYXRjaFRva2VuIiwidHlwIjoiSldUIn0.eyJ3YXRjaFRva2VuIjp7ImNhbGxTaWduIjoiS1ROViIsImRldmljZSI6IkFMTCIsImJhbmR3aWR0aCI6Ik1BU1RFUiIsImNvdW50cnkiOiJVU0EiLCJ1c2VySWQiOiI2MTliNTg3MWJhZmY3MTAwMDFkMTQzNDIiLCJyZXF1ZXN0VHlwZSI6ImxpdmUiLCJyZWdpb24iOiJ3ZXN0In0sImhvbWVaaXAiOiI4OTAzMiIsImdlb1ppcCI6Ijg5MTAxIn0.j9AhzliF_tqiQD6GCwDkM_A2QN6VwzhU3-sdWA4C5AE
2021-12-16 13:03:31,922 XstreamDL base.py 18 : DEBUG  fix name before: master
2021-12-16 13:03:31,922 XstreamDL base.py 23 : DEBUG  fix name after: master
2021-12-16 13:03:31,922 XstreamDL base.py 63 : DEBUG  parse uri result:
    name master
    home_url https://playlist.fubo.tv
    base_url https://playlist.fubo.tv
2021-12-16 13:03:31,923 XstreamDL base.py 28 : DEBUG  save content to D:/XstreamDL-CLI-master/XstreamDL-CLI-master/Downloads/master.mpd, size 8326
2021-12-16 13:03:31,923 XstreamDL parser.py 52 : DEBUG  [fix_dash_base_url] previous_base_url https://playlist.fubo.tv
2021-12-16 13:03:31,923 XstreamDL parser.py 52 : DEBUG  [fix_dash_base_url] previous_base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:31,923 XstreamDL parser.py 52 : DEBUG  [fix_dash_base_url] previous_base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:31,923 XstreamDL parser.py 52 : DEBUG  [fix_dash_base_url] previous_base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:31,923 XstreamDL parser.py 198 : DEBUG  [DASHStream] base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:31,924 XstreamDL parser.py 339 : DEBUG  mpd.presentationTimeOffset 0 timescale 90000
2021-12-16 13:03:31,924 XstreamDL parser.py 340 : DEBUG  mpd.availabilityStartTime 1625039231.0 Period.start 0.0
2021-12-16 13:03:31,924 XstreamDL parser.py 341 : DEBUG  start_utctime 1625039261.0 current_utctime 1639602208.0
2021-12-16 13:03:31,924 XstreamDL parser.py 347 : DEBUG  set base_time 1310664995640 target_r 22
2021-12-16 13:03:31,924 XstreamDL parser.py 52 : DEBUG  [fix_dash_base_url] previous_base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:31,924 XstreamDL parser.py 198 : DEBUG  [DASHStream] base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:31,924 XstreamDL parser.py 339 : DEBUG  mpd.presentationTimeOffset 0 timescale 90000
2021-12-16 13:03:31,924 XstreamDL parser.py 340 : DEBUG  mpd.availabilityStartTime 1625039231.0 Period.start 0.0
2021-12-16 13:03:31,924 XstreamDL parser.py 341 : DEBUG  start_utctime 1625039261.0 current_utctime 1639602208.0
2021-12-16 13:03:31,924 XstreamDL parser.py 347 : DEBUG  set base_time 1310664995640 target_r 22
2021-12-16 13:03:31,924 XstreamDL parser.py 52 : DEBUG  [fix_dash_base_url] previous_base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:31,924 XstreamDL parser.py 198 : DEBUG  [DASHStream] base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:31,924 XstreamDL parser.py 339 : DEBUG  mpd.presentationTimeOffset 0 timescale 90000
2021-12-16 13:03:31,924 XstreamDL parser.py 340 : DEBUG  mpd.availabilityStartTime 1625039231.0 Period.start 0.0
2021-12-16 13:03:31,924 XstreamDL parser.py 341 : DEBUG  start_utctime 1625039261.0 current_utctime 1639602208.0
2021-12-16 13:03:31,924 XstreamDL parser.py 347 : DEBUG  set base_time 1310664995640 target_r 22
2021-12-16 13:03:31,924 XstreamDL parser.py 52 : DEBUG  [fix_dash_base_url] previous_base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:31,924 XstreamDL parser.py 198 : DEBUG  [DASHStream] base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:31,924 XstreamDL parser.py 339 : DEBUG  mpd.presentationTimeOffset 0 timescale 90000
2021-12-16 13:03:31,925 XstreamDL parser.py 340 : DEBUG  mpd.availabilityStartTime 1625039231.0 Period.start 0.0
2021-12-16 13:03:31,925 XstreamDL parser.py 341 : DEBUG  start_utctime 1625039261.0 current_utctime 1639602208.0
2021-12-16 13:03:31,925 XstreamDL parser.py 347 : DEBUG  set base_time 1310664995640 target_r 22
2021-12-16 13:03:31,925 XstreamDL parser.py 52 : DEBUG  [fix_dash_base_url] previous_base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:31,925 XstreamDL parser.py 198 : DEBUG  [DASHStream] base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:31,925 XstreamDL parser.py 339 : DEBUG  mpd.presentationTimeOffset 0 timescale 90000
2021-12-16 13:03:31,925 XstreamDL parser.py 340 : DEBUG  mpd.availabilityStartTime 1625039231.0 Period.start 0.0
2021-12-16 13:03:31,925 XstreamDL parser.py 341 : DEBUG  start_utctime 1625039261.0 current_utctime 1639602208.0
2021-12-16 13:03:31,925 XstreamDL parser.py 347 : DEBUG  set base_time 1310664995640 target_r 22
2021-12-16 13:03:31,925 XstreamDL parser.py 52 : DEBUG  [fix_dash_base_url] previous_base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:31,925 XstreamDL parser.py 52 : DEBUG  [fix_dash_base_url] previous_base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:31,925 XstreamDL parser.py 198 : DEBUG  [DASHStream] base_url https://gcs-streams-prod.fubo.tv/KTNV/D2580/
2021-12-16 13:03:31,925 XstreamDL parser.py 339 : DEBUG  mpd.presentationTimeOffset 0 timescale 48000
2021-12-16 13:03:31,925 XstreamDL parser.py 340 : DEBUG  mpd.availabilityStartTime 1625039231.0 Period.start 0.0
2021-12-16 13:03:31,925 XstreamDL parser.py 341 : DEBUG  start_utctime 1625039261.0 current_utctime 1639602208.0
2021-12-16 13:03:31,925 XstreamDL parser.py 347 : DEBUG  set base_time 699021332543 target_r 22
2021-12-16 13:03:31,926 XstreamDL downloader.py 271 : DEBUG  selected is ['0_Video1_5_480x270', '0_Video1_4_768x432', '0_Video1_3_960x540', '0_Video1_2_1024x576', '0_Video1_1_1280x720', '1_Audio2_6']
2021-12-16 13:03:31,928 XstreamDL downloader.py 297 : INFO  master_video_H264_480x270_385.00kbps 下载开始.
2021-12-16 13:03:31,930 XstreamDL downloader.py 398 : DEBUG  downloaded count 0, downloaded size 0, left count 11
2021-12-16 13:03:31,930 XstreamDL downloader.py 409 : INFO  11 tasks start
2021-12-16 13:03:32,928 XstreamDL downloader.py 423 : DEBUG  0001.mp4v status 403, https://gcs-streams-prod.fubo.tv/KTNV/D2580/video-385000-1310664995640.mp4v
2021-12-16 13:03:32,928 XstreamDL downloader.py 439 : DEBUG  0001.mp4v response Content-length => 485
2021-12-16 13:03:32,932 XstreamDL downloader.py 423 : DEBUG  0000.mp4v status 403, https://gcs-streams-prod.fubo.tv/KTNV/D2580/video-385000-1310664635280.mp4v
2021-12-16 13:03:32,932 XstreamDL downloader.py 439 : DEBUG  0000.mp4v response Content-length => 485
2021-12-16 13:03:32,957 XstreamDL downloader.py 423 : DEBUG  init.mp4 status 403, https://gcs-streams-prod.fubo.tv/KTNV/D2580/video-385000-init.mp4
2021-12-16 13:03:32,957 XstreamDL downloader.py 439 : DEBUG  init.mp4 response Content-length => 485
2021-12-16 13:03:32,958 XstreamDL downloader.py 423 : DEBUG  0002.mp4v status 403, https://gcs-streams-prod.fubo.tv/KTNV/D2580/video-385000-1310665356000.mp4v
2021-12-16 13:03:32,958 XstreamDL downloader.py 439 : DEBUG  0002.mp4v response Content-length => 484
2021-12-16 13:03:33,910 XstreamDL downloader.py 423 : DEBUG  0004.mp4v status 403, https://gcs-streams-prod.fubo.tv/KTNV/D2580/video-385000-1310666076720.mp4v
2021-12-16 13:03:33,911 XstreamDL downloader.py 439 : DEBUG  0004.mp4v response Content-length => 484
2021-12-16 13:03:33,912 XstreamDL downloader.py 423 : DEBUG  0003.mp4v status 403, https://gcs-streams-prod.fubo.tv/KTNV/D2580/video-385000-1310665716360.mp4v
2021-12-16 13:03:33,912 XstreamDL downloader.py 439 : DEBUG  0003.mp4v response Content-length => 485
2021-12-16 13:03:33,955 XstreamDL downloader.py 423 : DEBUG  0005.mp4v status 403, https://gcs-streams-prod.fubo.tv/KTNV/D2580/video-385000-1310666437080.mp4v
2021-12-16 13:03:33,955 XstreamDL downloader.py 439 : DEBUG  0005.mp4v response Content-length => 485
2021-12-16 13:03:33,963 XstreamDL downloader.py 423 : DEBUG  0006.mp4v status 403, https://gcs-streams-prod.fubo.tv/KTNV/D2580/video-385000-1310666797440.mp4v
2021-12-16 13:03:33,963 XstreamDL downloader.py 439 : DEBUG  0006.mp4v response Content-length => 485
2021-12-16 13:03:34,879 XstreamDL downloader.py 423 : DEBUG  0007.mp4v status 403, https://gcs-streams-prod.fubo.tv/KTNV/D2580/video-385000-1310667157800.mp4v
2021-12-16 13:03:34,880 XstreamDL downloader.py 439 : DEBUG  0007.mp4v response Content-length => 485
2021-12-16 13:03:34,920 XstreamDL downloader.py 423 : DEBUG  0008.mp4v status 403, https://gcs-streams-prod.fubo.tv/KTNV/D2580/video-385000-1310667518160.mp4v
2021-12-16 13:03:34,920 XstreamDL downloader.py 439 : DEBUG  0008.mp4v response Content-length => 485
2021-12-16 13:03:34,935 XstreamDL downloader.py 423 : DEBUG  0009.mp4v status 403, https://gcs-streams-prod.fubo.tv/KTNV/D2580/video-385000-1310667878520.mp4v
2021-12-16 13:03:34,935 XstreamDL downloader.py 470 : ERROR  ! -> https://gcs-streams-prod.fubo.tv/KTNV/D2580/video-385000-1310667878520.mp4v
Traceback (most recent call last):
  File "D:\XstreamDL-CLI-master\XstreamDL-CLI-master\XstreamDL_CLI\downloader.py", line 427, in download
    self.xprogress.decrease_total_count()
  File "D:\XstreamDL-CLI-master\XstreamDL-CLI-master\XstreamDL_CLI\downloader.py", line 189, in decrease_total_count
    self.update_progress(self.downloaded_count, self.total_size, self.downloaded_size)
  File "D:\XstreamDL-CLI-master\XstreamDL-CLI-master\XstreamDL_CLI\downloader.py", line 197, in update_progress
    progress = downloaded_count / self.total_count
ZeroDivisionError: division by zero
2021-12-16 13:03:34,937 XstreamDL downloader.py 383 : ERROR  STATUS_SKIP 出现未知status 取消全部下载任务

`

**Comment by xhlove** [comment]
访问日志中的链接会发现返回的是

Error 403 no credentials to authenticate
no credentials to authenticate

也就是说403是因为鉴权失败，请按照反馈要点的说明检查是否缺少referer，cookie等header

或者对比正确的实际链接缺少一部分，则看看--url-patch使用

请仔细阅读理解readme的说明，再进行测试与反馈。

**Comment by 362227** [comment]
用了--url-patch 正常了
