### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by ReiDoBrega** [xhlove/XstreamDL-CLI#39]
MPD URL: https://skylatam-vod4.akamaized.net/sky/007/1f201578-c5fe-4f0c-80a5-c87ede3451b3/dash/001/1f201578-c5fe-4f0c-80a5-c87ede3451b3.mpd

2022-01-16 20:39:47,189 XstreamDL log.py 41 : INFO  log file -> C:/Users/Administrator/Downloads/XstreamDL-CLI-1.3.8/XstreamDL-CLI-1.3.8/logs/XstreamDL-2022-01-16_203947.log
2022-01-16 20:39:47,196 XstreamDL cli.py 152 : INFO  set URI to ['https://skylatam-vod4.akamaized.net/sky/007/1f201578-c5fe-4f0c-80a5-c87ede3451b3/dash/001/1f201578-c5fe-4f0c-80a5-c87ede3451b3.mpd']
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Downloads\XstreamDL-CLI-1.3.8\XstreamDL-CLI-1.3.8\XstreamDL_CLI\__main__.py", line 4, in <module>
    cli.main()
  File "C:\Users\Administrator\Downloads\XstreamDL-CLI-1.3.8\XstreamDL-CLI-1.3.8\XstreamDL_CLI\cli.py", line 154, in main
    daemon.daemon()
  File "C:\Users\Administrator\Downloads\XstreamDL-CLI-1.3.8\XstreamDL-CLI-1.3.8\XstreamDL_CLI\daemon.py", line 30, in daemon
    streams = extractor.fetch_metadata(self.args.URI[0])
  File "C:\Users\Administrator\Downloads\XstreamDL-CLI-1.3.8\XstreamDL-CLI-1.3.8\XstreamDL_CLI\extractor.py", line 48, in fetch_metadata
    return self.raw2streams('url', *loop.run_until_complete(self.fetch(uri)), parent_stream)
  File "C:\Users\Administrator\Downloads\XstreamDL-CLI-1.3.8\XstreamDL-CLI-1.3.8\XstreamDL_CLI\extractor.py", line 95, in raw2streams
    return self.parse_as_dash(uri_type, uri, content, parent_stream)
  File "C:\Users\Administrator\Downloads\XstreamDL-CLI-1.3.8\XstreamDL-CLI-1.3.8\XstreamDL_CLI\extractor.py", line 127, in parse_as_dash
    streams = self.parser.parse(uri, content)
  File "C:\Users\Administrator\Downloads\XstreamDL-CLI-1.3.8\XstreamDL-CLI-1.3.8\XstreamDL_CLI\extractors\dash\parser.py", line 132, in parse
    return self.walk_period(mpd, uri_item.new_base_url(base_url))
  File "C:\Users\Administrator\Downloads\XstreamDL-CLI-1.3.8\XstreamDL-CLI-1.3.8\XstreamDL_CLI\extractors\dash\parser.py", line 149, in walk_period
    _streams = self.walk_adaptationset(period, len(streams), uri_item.new_base_url(base_url))
  File "C:\Users\Administrator\Downloads\XstreamDL-CLI-1.3.8\XstreamDL-CLI-1.3.8\XstreamDL_CLI\extractors\dash\parser.py", line 177, in walk_adaptationset
    _streams = self.walk_representation(adaptationset, period, sindex + len(streams), current_uri_item)
  File "C:\Users\Administrator\Downloads\XstreamDL-CLI-1.3.8\XstreamDL-CLI-1.3.8\XstreamDL_CLI\extractors\dash\parser.py", line 254, in walk_representation
    self.generate_v1(period, representation.id, segmenttemplates[0], stream)
  File "C:\Users\Administrator\Downloads\XstreamDL-CLI-1.3.8\XstreamDL-CLI-1.3.8\XstreamDL_CLI\extractors\dash\parser.py", line 405, in generate_v1
    repeat = math.ceil(period.duration / interval)
ZeroDivisionError: float division by zero

**Comment by xhlove** [comment]
bug fixed https://github.com/xhlove/XstreamDL-CLI/commit/ef983956b1072aec33a5324a81004a5089c04b1a

![image](https://user-images.githubusercontent.com/48152166/150144130-60483bdc-842b-4e3d-95f9-13a2262b44f1.png)

and the subtitle link is broken, ignore that error

![image](https://user-images.githubusercontent.com/48152166/150144328-11f0d822-717c-4936-8d6e-fdd576cc4cd2.png)

**Comment by ReiDoBrega** [comment]
OK, thanks for the fix xhlove
