### ISSUE TITLE
--live-duration has been set but still getting no attribute 'timestamp'

### ISSUE THREAD

**Issue by samleong123** [xhlove/XstreamDL-CLI#40]
您好，不好意思打扰了
想请问 Key & Key ID 都放了 
``` --live-duration ``` 也放了可是还是提示 ```AttributeError: 'str' object has no attribute 'timestamp'
[2588] Failed to execute script '__main__' due to unhandled exception! ```
具体如下：
``` XStreamDL-CLI_v1.4.0.exe  --live --live-duration 00:05:00 --live-refresh-interval 1 --key c423a2f1a21f4c89bee94b03a1375041:0a19349f53ae743498e3003d9f816876 "https://rest-as.ott.kaltura.com/api_v3/service/assetFile/action/playManifest/partnerId/147/assetId/340313/assetType/media/assetFileId/11460225/contextType/PLAYBACK/isAltUrl/False/a.mpd"
2022-02-14 18:08:25,626 XstreamDL log.py 41 : INFO  log file -> C:/Users/Sam Sam/Desktop/Widevine Livestream Test/logs/XstreamDL-2022-02-14_180825.log
2022-02-14 18:08:25,628 XstreamDL default.py 19 : WARNING  headers is not exists, put your config file to C:/Users/Sam Sam/Desktop
2022-02-14 18:08:25,629 XstreamDL cli.py 158 : INFO  use 1.4.0, set URI to ['https://rest-as.ott.kaltura.com/api_v3/service/assetFile/action/playManifest/partnerId/147/assetId/340313/assetType/media/assetFileId/11460225/contextType/PLAYBACK/isAltUrl/False/a.mpd']
Traceback (most recent call last):
  File "XstreamDL_CLI\__main__.py", line 4, in <module>
  File "XstreamDL_CLI\cli.py", line 161, in main
  File "XstreamDL_CLI\daemon.py", line 30, in daemon
  File "XstreamDL_CLI\extractor.py", line 48, in fetch_metadata
  File "XstreamDL_CLI\extractor.py", line 95, in raw2streams
  File "XstreamDL_CLI\extractor.py", line 127, in parse_as_dash
  File "XstreamDL_CLI\extractors\dash\parser.py", line 133, in parse
  File "XstreamDL_CLI\extractors\dash\parser.py", line 150, in walk_period
  File "XstreamDL_CLI\extractors\dash\parser.py", line 178, in walk_adaptationset
  File "XstreamDL_CLI\extractors\dash\parser.py", line 242, in walk_representation
  File "XstreamDL_CLI\extractors\dash\parser.py", line 318, in walk_segmenttemplate
  File "XstreamDL_CLI\extractors\dash\parser.py", line 328, in walk_segmenttimeline
  File "XstreamDL_CLI\extractors\dash\parser.py", line 358, in walk_s
AttributeError: 'str' object has no attribute 'timestamp'
[2588] Failed to execute script '__main__' due to unhandled exception! ```

是我的指令有问题吗？版本为 v1.4.0
感谢

**Comment by xhlove** [comment]
所以你的指令呢。。

**Comment by xhlove** [comment]
https://github.com/xhlove/XstreamDL-CLI/actions/runs/1840846834 应该修复好了，你可以用这个测试下

**Comment by samleong123** [comment]
> 所以你的指令呢。。

抱歉没发现您的回复

```XStreamDL-CLI_v1.4.0.exe  --live --live-duration 00:05:00 --live-refresh-interval 1 --key c423a2f1a21f4c89bee94b03a1375041:0a19349f53ae743498e3003d9f816876 "https://rest-as.ott.kaltura.com/api_v3/service/assetFile/action/playManifest/partnerId/147/assetId/340313/assetType/media/assetFileId/11460225/contextType/PLAYBACK/isAltUrl/False/a.mpd"```

我现在尝试新的版本，谢谢您

**Comment by samleong123** [comment]
> https://github.com/xhlove/XstreamDL-CLI/actions/runs/1840846834 应该修复好了，你可以用这个测试下
> 
> * https://github.com/xhlove/XstreamDL-CLI/suites/5296889162/artifacts/164299692

您好，这个版本经过实测已经修复此问题，谢谢!
![image](https://user-images.githubusercontent.com/58818070/153861127-e03141c2-8283-4d68-87f9-4636dbd6ad39.png)
