### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Kuju29** [xhlove/XstreamDL-CLI#51]
```
01:39:09.461 XstreamDL_CLI\headers\default.py:26 DEBUG: use headers:
{
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36"
}
01:39:09.462 XstreamDL_CLI\cli.py:77 DEBUG: ffmpeg C:/Users/plan2/Downloads/test/XstreamDL-CLI-master/binaries/ffmpeg.exe
01:39:09.462 XstreamDL_CLI\cli.py:78 DEBUG: mp4decrypt C:/Users/plan2/Downloads/test/XstreamDL-CLI-master/binaries/mp4decrypt.exe
01:39:09.462 XstreamDL_CLI\cli.py:79 DEBUG: mp4box C:/Users/plan2/Downloads/test/XstreamDL-CLI-master/binaries/mp4box.exe
01:39:09.462 XstreamDL_CLI\cli.py:161 INFO: use 1.4.1, set URI to ['https://cdn208.stm.trueid.net/svod_wv/ASS202005000380_m_auto.smil/manifest.mpd?appid=trueid&type=svod&visitor=web&drm=wv3&uid=108364973&did=MTY0OTYxNDE0Mg&sid=aafbc4170f&rt=1649614141&tk=ylwsz0dc3gEViS4KceleacXkBbIm1pa4r1g9i5bH7zQ']
01:39:09.463 XstreamDL_CLI\cli.py:162 DEBUG: args => Namespace(version=False, help=False, speed_up=False, speed_up_left=10, live=False, compare_with_url=False, dont_split_discontinuity=False, name_from_url=False, live_duration=0.0, live_utc_offset=0, live_refresh_interval=3, name='', base_url='', ad_keyword='', resolution='', best_quality=True, video_only=False, audio_only=False, all_videos=False, all_audios=False, service='', save_dir=WindowsPath('Downloads'), select=True, multi_s=False, disable_force_close=False, limit_per_host=4, headers={'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36'}, url_patch='', overwrite=False, raw_concat=False, disable_auto_concat=False, enable_auto_delete=False, disable_auto_decrypt=False, key='67e5babd0e785cd0bccdbae46f10b3c6:ac9cac0caf7dffd96e32e1ea0bd8c238', b64key=None, hexiv=None, proxy='', disable_auto_exit=True, parse_only=False, show_init=False, index_to_name=False, log_level='INFO', redl_code=[], hide_load_metadata=False, URI=['https://cdn208.stm.trueid.net/svod_wv/ASS202005000380_m_auto.smil/manifest.mpd?appid=trueid&type=svod&visitor=web&drm=wv3&uid=108364973&did=MTY0OTYxNDE0Mg&sid=aafbc4170f&rt=1649614141&tk=ylwsz0dc3gEViS4KceleacXkBbIm1pa4r1g9i5bH7zQ'], ffmpeg='C:/Users/plan2/Downloads/test/XstreamDL-CLI-master/binaries/ffmpeg.exe', mp4decrypt='C:/Users/plan2/Downloads/test/XstreamDL-CLI-master/binaries/mp4decrypt.exe', mp4box='C:/Users/plan2/Downloads/test/XstreamDL-CLI-master/binaries/mp4box.exe')
01:39:09.667 XstreamDL_CLI\extractors\base.py:36 DEBUG: start parse uri for: https://cdn208.stm.trueid.net/svod_wv/ASS202005000380_m_auto.smil/manifest.mpd?appid=trueid&type=svod&visitor=web&drm=wv3&uid=108364973&did=MTY0OTYxNDE0Mg&sid=aafbc4170f&rt=1649614141&tk=ylwsz0dc3gEViS4KceleacXkBbIm1pa4r1g9i5bH7zQ
01:39:09.667 XstreamDL_CLI\extractors\base.py:64 DEBUG: parse uri result:
    name manifest
    home_url https://cdn208.stm.trueid.net
    base_url https://cdn208.stm.trueid.net/svod_wv/ASS202005000380_m_auto.smil
01:39:09.667 XstreamDL_CLI\extractors\base.py:29 DEBUG: save content to C:/Users/plan2/Downloads/test/XstreamDL-CLI-master/Downloads/manifest.mpd, size 28834
01:39:09.672 XstreamDL_CLI\extractors\dash\parser.py:201 DEBUG: current_base_url https://cdn208.stm.trueid.net/svod_wv/ASS202005000380_m_auto.smil
01:39:09.675 XstreamDL_CLI\extractors\dash\parser.py:201 DEBUG: current_base_url https://cdn208.stm.trueid.net/svod_wv/ASS202005000380_m_auto.smil
01:39:09.678 XstreamDL_CLI\extractors\dash\parser.py:201 DEBUG: current_base_url https://cdn208.stm.trueid.net/svod_wv/ASS202005000380_m_auto.smil
01:39:09.680 XstreamDL_CLI\extractors\dash\parser.py:201 DEBUG: current_base_url https://cdn208.stm.trueid.net/svod_wv/ASS202005000380_m_auto.smil
01:39:09.683 XstreamDL_CLI\extractors\dash\parser.py:201 DEBUG: current_base_url https://cdn208.stm.trueid.net/svod_wv/ASS202005000380_m_auto.smil
01:39:09.686 XstreamDL_CLI\extractors\dash\parser.py:201 DEBUG: current_base_url https://cdn208.stm.trueid.net/svod_wv/ASS202005000380_m_auto.smil
01:39:09.689 XstreamDL_CLI\extractors\dash\parser.py:201 DEBUG: current_base_url https://cdn208.stm.trueid.net/svod_wv/ASS202005000380_m_auto.smil
01:39:09.691 XstreamDL_CLI\extractors\dash\parser.py:201 DEBUG: current_base_url https://cdn208.stm.trueid.net/svod_wv/ASS202005000380_m_auto.smil
01:39:16.144 XstreamDL_CLI\downloader.py:284 DEBUG: selected is [6]
01:39:16.147 XstreamDL_CLI\downloader.py:310 INFO: manifest_audio_AAC_tha_125.44kbps download start.
01:39:16.155 XstreamDL_CLI\downloader.py:435 DEBUG: downloaded count 0, downloaded size 0, left count 357
01:39:16.156 XstreamDL_CLI\downloader.py:454 INFO: 357 tasks start
01:39:16.237 XstreamDL_CLI\downloader.py:487 DEBUG: init.m4s response Content-length => 782
01:39:16.237 XstreamDL_CLI\downloader.py:530 DEBUG: init.m4s download end, size => 782
01:39:16.249 XstreamDL_CLI\downloader.py:487 DEBUG: 0002.m4s response Content-length => 66409
01:39:16.251 XstreamDL_CLI\downloader.py:487 DEBUG: 0000.m4s response Content-length => 66318
01:39:16.251 XstreamDL_CLI\downloader.py:487 DEBUG: 0001.m4s response Content-length => 66035
01:39:16.263 XstreamDL_CLI\downloader.py:530 DEBUG: 0001.m4s download end, size => 66035
01:39:16.264 XstreamDL_CLI\downloader.py:530 DEBUG: 0000.m4s download end, size => 66318
01:39:16.264 XstreamDL_CLI\downloader.py:530 DEBUG: 0002.m4s download end, size => 66409
01:39:16.303 XstreamDL_CLI\downloader.py:487 DEBUG: 0003.m4s response Content-length => 66022
01:39:16.314 XstreamDL_CLI\downloader.py:530 DEBUG: 0003.m4s download end, size => 66022
01:39:16.325 XstreamDL_CLI\downloader.py:487 DEBUG: 0004.m4s response Content-length => 66341
01:39:16.327 XstreamDL_CLI\downloader.py:487 DEBUG: 0005.m4s response Content-length => 66053
01:39:16.327 XstreamDL_CLI\downloader.py:487 DEBUG: 0006.m4s response Content-length => 66381
01:39:16.335 XstreamDL_CLI\downloader.py:530 DEBUG: 0004.m4s download end, size => 66341
01:39:16.339 XstreamDL_CLI\downloader.py:530 DEBUG: 0005.m4s download end, size => 66053
01:39:16.340 XstreamDL_CLI\downloader.py:530 DEBUG: 0006.m4s download end, size => 66381
01:39:16.381 XstreamDL_CLI\downloader.py:487 DEBUG: 0007.m4s response Content-length => 66010
01:39:16.393 XstreamDL_CLI\downloader.py:530 DEBUG: 0007.m4s download end, size => 66010
01:39:16.394 XstreamDL_CLI\downloader.py:487 DEBUG: 0008.m4s response Content-length => 66387
01:39:16.397 XstreamDL_CLI\downloader.py:487 DEBUG: 0009.m4s response Content-length => 66005
01:39:16.400 XstreamDL_CLI\downloader.py:487 DEBUG: 0010.m4s response Content-length => 66395
01:39:16.405 XstreamDL_CLI\downloader.py:530 DEBUG: 0008.m4s download end, size => 66387
01:39:16.408 XstreamDL_CLI\downloader.py:530 DEBUG: 0009.m4s download end, size => 66005
01:39:16.412 XstreamDL_CLI\downloader.py:530 DEBUG: 0010.m4s download end, size => 66395
01:39:16.457 XstreamDL_CLI\downloader.py:487 DEBUG: 0011.m4s response Content-length => 66028
01:39:16.457 XstreamDL_CLI\downloader.py:519 ERROR: ! -> https://cdn208.stm.trueid.net/svod_wv/ASS202005000380_m_auto.smil/segment_ctaudio_ridp0aa0br125437_cs2112528_mpd.m4s?ccuid=c99i8jbgf2dbnh7e1vlg&appid=trueid&type=svod&visitor=web&drm=wv3&uid=108364973&did=MTY0OTYxNDE0Mg&sid=aafbc4170f&rt=1649614141&tk=ylwsz0dc3gEViS4KceleacXkBbIm1pa4r1g9i5bH7zQ
Traceback (most recent call last):
  File "C:\Users\plan2\Downloads\test\XstreamDL-CLI-master\XstreamDL_CLI\downloader.py", line 488, in download
    self.xprogress.update_total_size(stream.filesize)
  File "C:\Users\plan2\Downloads\test\XstreamDL-CLI-master\XstreamDL_CLI\downloader.py", line 195, in update_total_size
    self.update_progress(self.downloaded_count, self.total_size, self.downloaded_size)
  File "C:\Users\plan2\Downloads\test\XstreamDL-CLI-master\XstreamDL_CLI\downloader.py", line 223, in update_progress
    sys.stdout.write(text)
  File "C:\Users\plan2\AppData\Local\Programs\Python\Python310\lib\encodings\cp874.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2588' in position 35: character maps to <undefined>

```

**Comment by xhlove** [comment]
`export PYTHONIOENCODING=utf-8` first, then run command

**Comment by Kuju29** [comment]
it work thank you <3
