### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float' error

### ISSUE THREAD

**Issue by fogers777** [xhlove/XstreamDL-CLI#58]
Hello,

i have cloned the master branch and trying to run below command. Can't get it working.

python3 -m XstreamDL_CLI --key 22222:11111 --raw-concat --select --live --live-duration 02:00:00 "https://cdnlb.*.lt/live/***/**_**_**_HVC/***_***_DASH_AVC/***_**_**_HVC.mpd"

```11:53:02.712 XstreamDL_CLI/cli.py:168 INFO: use 1.4.3, set URI to ['https://cdnlb.*.lt/live/eds/**_**_**_HVC/***_***_DASH_AVC/***_**_**_HVC.mpd']
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/secret/Downloads/cdm/XstreamDL-CLI-master/XstreamDL_CLI/__main__.py", line 4, in <module>
    cli.main()
  File "/Users/secret/Downloads/cdm/XstreamDL-CLI-master/XstreamDL_CLI/cli.py", line 171, in main
    daemon.daemon()
  File "/Users/secret/Downloads/cdm/XstreamDL-CLI-master/XstreamDL_CLI/daemon.py", line 30, in daemon
    streams = extractor.fetch_metadata(self.args.URI[0])
  File "/Users/secret/Downloads/cdm/XstreamDL-CLI-master/XstreamDL_CLI/extractor.py", line 53, in fetch_metadata
    return self.raw2streams('url', *loop.run_until_complete(self.fetch(uri)), parent_stream)
  File "/Users/secret/Downloads/cdm/XstreamDL-CLI-master/XstreamDL_CLI/extractor.py", line 100, in raw2streams
    return self.parse_as_dash(uri_type, uri, content, parent_stream)
  File "/Users/secret/Downloads/cdm/XstreamDL-CLI-master/XstreamDL_CLI/extractor.py", line 132, in parse_as_dash
    streams = self.parser.parse(uri, content)
  File "/Users/secret/Downloads/cdm/XstreamDL-CLI-master/XstreamDL_CLI/extractors/dash/parser.py", line 135, in parse
    return self.walk_period(mpd, uri_item.new_base_url(base_url))
  File "/Users/secret/Downloads/cdm/XstreamDL-CLI-master/XstreamDL_CLI/extractors/dash/parser.py", line 152, in walk_period
    _streams = self.walk_adaptationset(period, len(streams), uri_item.new_base_url(base_url))
  File "/Users/secret/Downloads/cdm/XstreamDL-CLI-master/XstreamDL_CLI/extractors/dash/parser.py", line 180, in walk_adaptationset
    _streams = self.walk_representation(adaptationset, period, sindex + len(streams), current_uri_item)
  File "/Users/secret/Downloads/cdm/XstreamDL-CLI-master/XstreamDL_CLI/extractors/dash/parser.py", line 257, in walk_representation
    self.generate_v1(period, representation.id, segmenttemplates[0], stream)
  File "/Users/secret/Downloads/cdm/XstreamDL-CLI-master/XstreamDL_CLI/extractors/dash/parser.py", line 442, in generate_v1
    repeat = math.ceil(period.duration / interval)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'```

**Comment by xhlove** [comment]
fixed

- https://github.com/xhlove/XstreamDL-CLI/actions/runs/3090556762

if your timezone is not same as mpd server area, you need add `--live-utc-offset xxxx` option

download mpd file, you will see `publishTime`, e.g. `2022-09-20T13:38:09.533639Z`

but my local time is `2022-09-20 21:38:09`

21 - 13 = 8 hour = 8 * 60 * 60s = 28800

then, I need set `--live-utc-offset 28800`
