### ISSUE TITLE
--live returns an AssertionError

### ISSUE THREAD

**Issue by luixiuno** [xhlove/XstreamDL-CLI#61]
```\XstreamDL-CLI_v1.4.3.exe --live --live-duration 00:00:00 --live-refresh-interval 3 --select --key STREAM_ID:STREAM_KEY --name azteca7-2 --limit-per-host 4 "https://live4-ott.izzigo.tv/out/u/dash/AZTECA-7-HD/default.mpd"
22:21:12.136 XstreamDL_CLI\headers\default.py:20 WARNING: headers is not exists, put your config file to C:/Users/0x00/Downloads
22:21:12.139 XstreamDL_CLI\cli.py:162 INFO: use 1.4.3, set URI to ['https://live4-ott.izzigo.tv/out/u/dash/AZTECA-7-HD/default.mpd']
Traceback (most recent call last):
  File "XstreamDL_CLI\__main__.py", line 4, in <module>
  File "XstreamDL_CLI\cli.py", line 165, in main
  File "XstreamDL_CLI\daemon.py", line 30, in daemon
  File "XstreamDL_CLI\extractor.py", line 53, in fetch_metadata
  File "XstreamDL_CLI\extractor.py", line 100, in raw2streams
  File "XstreamDL_CLI\extractor.py", line 132, in parse_as_dash
  File "XstreamDL_CLI\extractors\dash\parser.py", line 135, in parse
  File "XstreamDL_CLI\extractors\dash\parser.py", line 152, in walk_period
  File "XstreamDL_CLI\extractors\dash\parser.py", line 180, in walk_adaptationset
  File "XstreamDL_CLI\extractors\dash\parser.py", line 235, in walk_representation
  File "XstreamDL_CLI\extractors\dash\parser.py", line 324, in walk_segmenttimeline
  File "XstreamDL_CLI\extractors\dash\parser.py", line 377, in walk_s
AssertionError: audio_147682_spa=147200 report mpd to me, maybe need wait 21575.124229192734s
[6048] Failed to execute script '__main__' due to unhandled exception!```

**Comment by xbstory** [comment]
add `--live-utc-offset 21600`

or try N_m3u8DL-RE

**Comment by luixiuno** [comment]
@xhlove But what does live mode do? From what i see it cannot decrypt in realtime
